name: Build Plan van Aanpak PDF
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'procesproducten/plan-van-aanpak/*.md'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye-slim

    steps:
      - name: Cache LaTeX + Git packages
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt/archives
            /usr/share/texlive
          key: ${{ runner.os }}-texlive-v1

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-latex-extra \
            git
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Generate PDF
        working-directory: procesproducten/plan-van-aanpak
        run: |
          pandoc --defaults=pva-pdf.yaml $(cat include.txt)

      - name: Commit PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add procesproducten/plan-van-aanpak/Plan-van-Aanpak.pdf
          git commit -m "Update Plan van Aanpak PDF [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        continue-on-error: true  # in case PDF hasn't changed